### ISSUE TITLE
Get rid of mage and write a bash script ./task that takes an argument

### ISSUE THREAD

**Issue by 0pdd** [frou/yt2pod#16]
The puzzle `0-9ab305b9` from #0 has to be resolved: 

https://github.com/frou/yt2pod/blob/b7b558f5e31a36d7fcaee03e1afbd2e3d05e1ab3/Magefile.go#L13-L13

The puzzle was created by Duncan Holm on 09-Aug-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Abandoning
