### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by schafezp** [frou/yt2pod#2]
I noticed that you [indicated](https://news.ycombinator.com/item?id=18047094) you wanted to dockerize this application. It seems like a pretty simple Go single service application which could be expressed as a single Dockerfile and docker-compose.yml file. Since it's a single service docker-compose is not necessary but I find it to be a pleasant interface for spinning up / spinning down containers.To make the daemon work on startup the systemd service could instead call docker. Alternatively a restart policy could be used to automatically restart the container on boot although I'm [not sure if this is possible using docker-compose](https://forums.docker.com/t/how-to-handle-server-reboot-when-using-docker-compose/26374)

 Environment variables could perhaps be used to pass in various flag values.

Here is a [document about dockerizing go applications](https://thenewstack.io/dockerize-go-applications/)

I created this issue to keep track of the desired feature. I intend to submit a pull request at some point soon to resolve this issue unless you don't want outside help in which case feel free to close this issue.

**Comment by frou** [comment]
Zachary - I'm glad you're interested and certainly welcome your help to Dockerize this.

Even though the README has a section regarding `systemd`, I have never actually used systemd myself. That section was added by a GitHub contributor.

To run yt2pod on my own VPS, I have used Alpine Linux along with [this initscript](https://gist.github.com/frou/31f6b305f619d3bdb96f84c72150cc06). I know that Alpine Linux is popular in Docker land, so maybe it makes sense to partially reuse that. But I don't have a strong opinion.
