### ISSUE TITLE
Ampersands in titles are encoded twice

### ISSUE THREAD

**Issue by sabberworm** [frou/yt2pod#20]
When subscribing to a channel that has ampersands in the video titles (such as https://www.youtube.com/user/Filmanalyse), the podcast player shows `&amp;` instead of just `&` in the title.

**Comment by frou** [comment]
Thanks for noticing this. I suspect that string now being escaped as if it is HTML/XML is an undocumented change YouTube have made to their Data-API. But regardless, it's certainly possible to workaround that in code here.

**Comment by frou** [comment]
If you run go get with the -u flag (`go get -u github.com/frou/yt2pod`) it should download and build it again with the fix

**Comment by sabberworm** [comment]
Thanks!
