### ISSUE TITLE
Subscribe to different types of accounts

### ISSUE THREAD

**Issue by jxjxjhjh** [frou/yt2pod#24]
https://m.youtube.com/user/sun2823793
https://m.youtube.com/c/%E6%9E%9C%E5%AD%90GuoZi?disable_polymer=true&itct=CEAQ_FoYACITCPmv15GDk-8CFc4CrQYdNxwHVw%3D%3D
Can these two types of accounts be supported?

**Comment by frou** [comment]
> Can these two types of accounts be supported?

> https://m.youtube.com/user/sun2823793

In the config file, that channel should be `"yt_channel": "UCkHrq03gWLLx6vjS2DOJ8aA",` 

> https://m.youtube.com/c/%E6%9E%9C%E5%AD%90GuoZi?disable_polymer=true&itct=CEAQ_FoYACITCPmv15GDk-8CFc4CrQYdNxwHVw%3D%3D

...and this one... `"yt_channel": "UCwvApA-Fd8Zmn6EGWXQO0FA",`

**Comment by jxjxjhjh** [comment]
How to convert? I have other similar channel addresses that need to be converted.

**Comment by frou** [comment]
When I visit e.g. https://m.youtube.com/user/sun2823793 in a browser, the server automatically redirects me to:

<img width="562" alt="Screenshot 2021-03-03 at 14 44 06" src="https://user-images.githubusercontent.com/172663/109822648-10143900-7c2f-11eb-8e4f-2f584b75305d.png">

but you can also View Source (HTML) of the page and search for `"channelId"`

**Comment by jxjxjhjh** [comment]
I can’t start the docker container after the YouTube api is used up that day, hoping to improve it, because in this case, I can’t listen to the programs I have already obtained.

**Comment by frou** [comment]
Yep, I think there's too many people all using the same API Key that's in the example config file. If you [register](https://developers.google.com/youtube/registering_an_application) for an API Key yourself and keep it private then no limits will be exceeded.

**Comment by jxjxjhjh** [comment]
I used the one I applied for, and no more than one hundred projects would be oversubscribed.

**Comment by frou** [comment]
> I used the one I applied for, and no more than one hundred projects would be oversubscribed.

If using `"title_filter"`, the quota usage should hopefully be reduced by b7d4db47ca66d81b829c9a7a71710a96c40f729a

Also, setting `"check_interval_minutes"` to a higher number will obviously reduce quota usage too.
