### ISSUE TITLE
Videos get downloaded for all podcasts when only a single podcast is set to video mode

### ISSUE THREAD

**Issue by jxjxjhjh** [frou/yt2pod#27]
Add an ignore parameter and just don’t perform audio conversion.
After all, youtube is a video site, and a lot of content is mainly for watching videos.
I really hope to increase the video format.

**Comment by frou** [comment]
This is actually already possible, but just hasn't been documented.

Add `"vidya": true` to a podcast's config entry.

**Comment by jxjxjhjh** [comment]
{
            "name": "七年环球",
            "short_name": "7nhq",


            "yt_channel": "UCmFoIRFXkVZ_yLX8w8BaVAA",
            "title_filter": "",
            "vidya": true,


            "epoch": "2021-03-22"
        }

where error?

**Comment by jxjxjhjh** [comment]
After adding vidya: true to any item, all items become video instead of audio. Is it a bug?

**Comment by frou** [comment]
Yep, that's a bug. [it's being set on the outer cfg struct which gets shared between podcasts](https://github.com/frou/yt2pod/blob/24031995650e8667d2829ec70d51764a0156ea82/watcher.go#L66-L67)

**Comment by jxjxjhjh** [comment]
How long can this bug be fixed?

**Comment by frou** [comment]
Now that this feature is officially documented, the config file must use the correct spelling `"video"` instead of `"vidya"`
