### ISSUE TITLE
This error occurred recently

### ISSUE THREAD

**Issue by jxjxjhjh** [frou/yt2pod#34]
Hits in last 24h0m0s period by dir: map[/:39 /Content:1 /Content/css:1 /Css:1 /Home:1 /Home/Bind:1 /Home/Get:1 /Home/Index:1 /Promotions:1 /Public/Home/images/game:1 /Public/Home/js:1 /Public/Mobile/ecshe_css:1 /Public/Wchat/css:1 /Public/Wchat/js:1 /Public/css:2 /Public/home/js:1 /Public/home/wap/css:1 /Public/js:1 /Public/mobile/js:1 /Public/uploads/web:1 /Recruit:1 /Templates/user/js:1 /account:1 /anquan:1 /api:3 /api/Index:1 /api/currency:1 /api/index:1 /api/message:1 /api/mobile:1 /api/product:1 /api/site:1 /api/uploads:1 /api/v/index:1 /api/web/user:1 /assets/dist/static/js:1 /assets/js:1 /assets/room/css:1 /base:1 /common:1 /cq/css:1 /cscpLoginWeb/app:1 /cscpLoginWeb/scripts:1 /csjs:1 /css:3 /ep:23 /files:1 /home/login:1 /home/main:1 /iframe/rankgiftgotapi:1 /images:1 /index.php:1 /index/Mobile:2 /index/api:1 /index/index:1 /index/login:1 /infe/rest/fig/advertise:1 /infe/rest/flash:1 /ipl/app/flash/publicbmw/ball:1 /js:2 /lanren/css:1 /login/img/nyyh:2 /manager/js:1 /market:1 /market/market-ws:1 /melody/api/v1/pageconfig:1 /member/js:1 /meta:250 /mobile:1 /mobile/script:1 /mobile/v3:1 /nyyh:2 /portal/index:1 /public/admin.php/api/index:1 /public/css:1 /public/h5static/js:1 /public/img:1 /public/web/css/add:1 /public/web/js/add:1 /resources/css:1 /resources/main:1 /room:2 /s_api/basic/download:1 /script:1 /site:2 /skin/js:1 /static/admincp/js:1 /static/common/js:1 /static/css:1 /static/data:1 /static/guide:1 /static/home/css:1 /static/home/css2:1 /static/home/js:1 /static/home/static/js:1 /static/wap/css:1 /static/wap/js:1 /static/xianyu/js:1 /statics/js:1 /stock:1 /template/920ka/css:1 /template/920ka/js:1 /template/css:1 /template/js/comm:1 /user:3 /views/commData:1 /wap/trading:1 /web/api:1 /ws/index:1 /xy/image:1 /zz:1]

**Comment by jxjxjhjh** [comment]
Hits in last 24h0m0s period by dir: map[/:25 /ep:67 /meta:274]

**Comment by frou** [comment]
Those are just access logs, not errors. The first log shows that someone's automated scanner is scanning your server for common URLs

**Comment by jxjxjhjh** [comment]
This is docker logs. When I restart the container, I can get the video normally for the first time, but when the second time is set, I cannot get the video. The latest docker logs is such a log.

**Comment by frou** [comment]
If you want to fully understand this, you can read the source code [here](https://github.com/frou/yt2pod/blob/390f5c8342636dcc3ee65f8d40da7c8587ed9451/main.go#L90-L95) and [here](https://github.com/frou/yt2pod/blob/master/hits.go)
